name: Release python hops_deltalake

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./python

jobs:
  build-mac:
    name: PyPI release on Mac
    strategy:
      fail-fast: false
      matrix:
        target: [aarch64-apple-darwin]
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Publish to pypi (without sdist)
        uses: messense/maturin-action@v1
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        with:
          target: ${{ matrix.target }}
          command: publish
          args: --profile python-release-arm --skip-existing -m python/Cargo.toml --no-sdist

  build-manylinux-x86-64:
    name: PyPI release manylinux-2_28 x86_64
    strategy:
      fail-fast: false
      matrix:
        target: [ x86_64-unknown-linux-gnu ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Publish manylinux to pypi x86_64 (with sdist)
        uses: messense/maturin-action@v1
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        with:
          maturin-version: v1.6.0 # https://github.com/PyO3/maturin/issues/2154
          target: ${{ matrix.target }}
          command: publish
          manylinux: 2_28
          args: --profile python-release --skip-existing -m python/Cargo.toml
          # for openssl build
          before-script-linux: yum install -y perl-IPC-Cmd openssl-devel pkgconfig
